<?php
require_once 'db.php';
$db=get_db(); header('Content-Type: application/json');
function data_in(){ $j=json_decode(file_get_contents('php://input'),true); return is_array($j)?$j:$_POST; }
function ok($d=[]){ echo json_encode(['ok'=>true]+$d); exit; }
try{
 $a=$_REQUEST['action']??''; $d=data_in();
 switch($a){
  case 'add_client': $s=$db->prepare('INSERT INTO clients(name,phone,email,notes,created_at) VALUES(?,?,?,?,?)');$s->execute([$d['name']??'',$d['phone']??'',$d['email']??'',$d['notes']??'',now()]);ok(['id'=>$db->lastInsertId()]);
  case 'add_booking': $cid=(int)($d['client_id']??0);if(!$cid&&($d['client_name']??'')){ $q=$db->prepare('SELECT id FROM clients WHERE name=? LIMIT 1');$q->execute([$d['client_name']]);$cid=(int)$q->fetchColumn();if(!$cid){$q=$db->prepare('INSERT INTO clients(name,created_at) VALUES(?,?)');$q->execute([$d['client_name'],now()]);$cid=(int)$db->lastInsertId();}}$s=$db->prepare('INSERT INTO bookings(client_id,service,booked_date,duration,unit_price,amount,deposit,status,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([$cid,$d['service']??'', $d['booked_date']??'',(int)($d['duration']??60),(float)($d['unit_price']??0),(float)($d['amount']??0),(float)($d['deposit']??0),$d['status']??'pending',$d['notes']??'',now()]);ok(['id'=>$db->lastInsertId()]);
  case 'add_payment': $cid=(int)($d['client_id']??0);if(!$cid&&($d['client_name']??'')){ $q=$db->prepare('SELECT id FROM clients WHERE name=? LIMIT 1');$q->execute([$d['client_name']]);$cid=(int)$q->fetchColumn();if(!$cid){$q=$db->prepare('INSERT INTO clients(name,created_at) VALUES(?,?)');$q->execute([$d['client_name'],now()]);$cid=(int)$db->lastInsertId();}}$s=$db->prepare('INSERT INTO payments(booking_id,client_id,amount,method,status,invoice_reference,note,paid_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$d['booking_id']??null,$cid,(float)($d['amount']??0),$d['method']??'Card',$d['status']??'Paid',$d['invoice_reference']??'',$d['note']??'',now(),now()]);ok(['id'=>$db->lastInsertId()]);
  case 'add_product': $s=$db->prepare('INSERT INTO products(name,brand,category,quantity,max_quantity,expiry_date,created_at) VALUES(?,?,?,?,?,?,?)');$s->execute([$d['name']??'',$d['brand']??'',$d['category']??'',(int)($d['quantity']??0),(int)($d['max_quantity']??$d['quantity']??0),$d['expiry_date']??'',now()]);ok(['id'=>$db->lastInsertId()]);
  case 'upload_portfolio': if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK) throw new Exception('Select an image first');$dir=__DIR__.'/uploads';if(!is_dir($dir))mkdir($dir,0755,true);$ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['jpg','jpeg','png','webp']))throw new Exception('Use JPG, PNG, or WebP');$name=bin2hex(random_bytes(8)).'.'.$ext;$path=$dir.'/'.$name;if(!move_uploaded_file($_FILES['file']['tmp_name'],$path))throw new Exception('Upload failed');$s=$db->prepare('INSERT INTO portfolio(category,file_path,created_at) VALUES(?,?,?)');$s->execute([$_POST['category']??'Studio','uploads/'.$name,now()]);ok(['id'=>$db->lastInsertId(),'path'=>'uploads/'.$name]);
  case 'save_settings': $s=$db->prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at');foreach($d as $k=>$v){$s->execute([$k,is_scalar($v)?(string)$v:json_encode($v),now()]);}ok();
  case 'dashboard': $up=$db->query("SELECT b.*,c.name FROM bookings b JOIN clients c ON c.id=b.client_id WHERE date(b.booked_date)>=date('now') ORDER BY b.booked_date LIMIT 8")->fetchAll(PDO::FETCH_ASSOC);$rev=(float)$db->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='Paid'")->fetchColumn();$today=(int)$db->query("SELECT COUNT(*) FROM bookings WHERE date(booked_date)=date('now')")->fetchColumn();$clients=(int)$db->query("SELECT COUNT(*) FROM clients WHERE cancelled_at IS NULL")->fetchColumn();$avg=(float)$db->query('SELECT COALESCE(AVG(amount),0) FROM bookings')->fetchColumn();ok(['upcoming'=>$up,'revenue'=>$rev,'bookings_today'=>$today,'clients'=>$clients,'average_value'=>$avg]);
  case 'clients': ok(['clients'=>$db->query('SELECT * FROM clients WHERE cancelled_at IS NULL ORDER BY created_at DESC')->fetchAll(PDO::FETCH_ASSOC)]);
  case 'bookings': ok(['bookings'=>$db->query('SELECT b.*,c.name FROM bookings b JOIN clients c ON c.id=b.client_id ORDER BY booked_date DESC')->fetchAll(PDO::FETCH_ASSOC)]);
  case 'products': ok(['products'=>$db->query('SELECT * FROM products ORDER BY category,name')->fetchAll(PDO::FETCH_ASSOC)]);
  case 'payments': ok(['payments'=>$db->query('SELECT p.*,c.name FROM payments p JOIN clients c ON c.id=p.client_id ORDER BY paid_at DESC')->fetchAll(PDO::FETCH_ASSOC)]);
  case 'portfolio': ok(['portfolio'=>$db->query('SELECT * FROM portfolio ORDER BY created_at DESC')->fetchAll(PDO::FETCH_ASSOC)]);
  case 'cancel_booking': $s=$db->prepare("UPDATE bookings SET status='cancelled' WHERE id=?");$s->execute([(int)($_REQUEST['id']??0)]);ok();
  case 'update_booking_status': $s=$db->prepare("UPDATE bookings SET status=? WHERE id=?");$s->execute([$d['status']??$_REQUEST['status']??'confirmed',(int)($d['id']??$_REQUEST['id']??0)]);ok();
  case 'cancel_client': $s=$db->prepare('UPDATE clients SET cancelled_at=? WHERE id=?');$s->execute([now(),(int)($_REQUEST['id']??0)]);ok();
  default: throw new Exception('Unknown action');
 }
}catch(Throwable $e){http_response_code(500);echo json_encode(['ok'=>false,'error'=>$e->getMessage()]);}
