name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v6

      - name: Deploy to InfinityFree
        uses: step-security/ftp-deploy-action@v4
        with:
          server: ftpupload.net
          username: ${{ secrets.INFINITY_USERNAME }}
          password: ${{ secrets.INFINITY_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            config.php
            data/**
